### ISSUE TITLE
Great theme. How to make jupyter standalone?

### ISSUE THREAD

**Issue by astrobdr** [nimbous/jupyter-calm-theme#2]
In the preview, it looks like you have jupyter lab as a standalone application. I would like to do this myself. Can you tell me how you achieved this look?

**Comment by atillaguzel** [comment]
It is actually just Chrome trick. On a Mac you can achieve this by following the steps below:
- Run jupyter lab using Chrome and go to Jupyter tab, 
- Click the 3 dot on the top-right-hand corner
- Select More tools -> Create a shortcut -> Tick Open as windows

Your jupyter lab should open like a standalone App. I believe the steps are similar on a Windows or Linux machine.

**Comment by shatz01** [comment]
Wow I cant believe ive never known this lol. Big thanks

**Comment by atillaguzel** [comment]
:) I had the same feeling when I first came to know about it.
